routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.pages.home');
})->name('home');

Route::get('/abstract', function () {
    return view('frontend.pages.abstract');
})->name('abstract');
Route::get('/workshop', function () {
    return view('frontend.pages.workshop');
})->name('workshop');








Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
//   ->middleware('role:admin')
    ->group(function (){

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/registered-user', 'RegisteredUserController@index')->name('registered-user');
        Route::get('/registered-user/{id}', 'RegisteredUserController@show')->name('registered-user.show');
        Route::get('/abstract-submitted', 'AbstractController@index')->name('abstract-submitted');
        Route::get('/abstract-submitted/{id}', 'AbstractController@show')->name('abstract-submitted.show');
        Route::get('/workshop', 'WorkshopController@index')->name('workshop');
        Route::get('/workshop/{id}', 'WorkshopController@show')->name('workshop.show');
        Route::get('/subscriber', 'SubscriberController@index')->name('subscriber');
        Route::get('/subscriber/export', 'SubscriberController@export')->name('subscriber.export');

    Route::get('/add-important-date', 'ImportantDateController@create')->name('date.create');
    Route::post('/add-important-date', 'ImportantDateController@store')->name('date.store');
    Route::get('/important-dates', 'ImportantDateController@index')->name('dates');
    Route::post('/important-date-update', 'ImportantDateController@update')->name('date.update');
    Route::get('/important-date-destroy/{id}', 'ImportantDateController@destroy')->name('date.destroy');
    Route::get('/important-date-edit/{id}', 'ImportantDateController@show')->name('date.edit');

        Route::get('/add-speech', 'SpeechController@create')->name('speech.create');
        Route::post('/add-speech', 'SpeechController@store')->name('speech.store');
        Route::get('/speeches', 'SpeechController@index')->name('speeches');
        Route::post('/speech-update', 'SpeechController@update')->name('speech.update');
        Route::get('/speech-destroy/{id}', 'SpeechController@destroy')->name('speech.destroy');
        Route::get('/speech-edit/{id}', 'SpeechController@show')->name('speech.edit');

    Route::get('/add-slider', 'SliderController@create')->name('slider.create');
    Route::post('/add-slider', 'SliderController@store')->name('slider.store');
    Route::get('/sliders', 'SliderController@index')->name('sliders');
    Route::post('/slider-update', 'SliderController@update')->name('slider.update');
    Route::get('/slider-destroy/{id}', 'SliderController@destroy')->name('slider.destroy');
    Route::get('/slider-edit/{id}', 'SliderController@show')->name('slider.edit');


        Route::get('/add-schedule', 'ScheduleController@create')->name('schedule.create');
        Route::post('/add-schedule', 'ScheduleController@store')->name('schedule.store');
        Route::get('/schedules', 'ScheduleController@index')->name('schedules');
        Route::post('/schedule-update', 'ScheduleController@update')->name('schedule.update');
        Route::get('/schedule-destroy/{id}', 'ScheduleController@destroy')->name('schedule.destroy');
        Route::get('/schedule-edit/{id}', 'ScheduleController@show')->name('schedule.edit');






    });

Route::namespace('Backend')
  /*    ->middleware('role:user')*/
    ->group(function (){

        Route::get('/abstract','AbstractController@frontend' )->name('abstract.frontend');
        Route::post('/abstract','AbstractController@store' )->name('abstract.store');

        Route::get('/workshop','WorkshopController@frontend' )->name('workshop.frontend');
        Route::post('/workshop','WorkshopController@store' )->name('workshop.store');
    });


Route::name('frontend.')
        ->namespace('Frontend')
        ->group(function (){
            Route::get('/','IndexController@index' )->name('index');

            Route::get('/registration', function () {
                return view('frontend.pages.registration-detail');
            })->name('registration');

            Route::get('/dashboard','SinglePageController@dashboard' )->name('dashboard');

            Route::get('invitation', 'SinglePageController@invitation')->name('invitation');
            Route::get('tourism', 'SinglePageController@tourism')->name('tourism');
            Route::get('transportation', 'SinglePageController@transportation')->name('transportation');
            Route::get('attendees', 'SinglePageController@attendees')->name('attendees');
            Route::get('accommodations', 'SinglePageController@accommodations')->name('accommodations');


            Route::get('/payment-success','SinglePageController@payment_success' )->name('payment.success');
            Route::get('/payment-failed','SinglePageController@payment_fail' )->name('payment.failed');

            Route::get('/important-dates','SinglePageController@dates' )->name('dates');
            Route::get('/contact','SinglePageController@contact' )->name('contact');

            Route::post('/subscriber','IndexController@subscriber' )->name('subscriber.store');
        });



// SSLCOMMERZ Start
Route::get('/example1', 'SslCommerzPaymentController@exampleEasyCheckout');
Route::get('/example2', 'SslCommerzPaymentController@exampleHostedCheckout');

Route::post('/pay', 'SslCommerzPaymentController@index');
Route::post('/pay-via-ajax', 'SslCommerzPaymentController@payViaAjax');

Route::post('/success', 'SslCommerzPaymentController@success');
Route::post('/fail', 'SslCommerzPaymentController@fail');
Route::post('/cancel', 'SslCommerzPaymentController@cancel');

Route::post('/ipn', 'SslCommerzPaymentController@ipn');
//SSLCOMMERZ END

resources/views/frontend/theme/ui/includes/flash-message.blade.php
<div class="container text-center">



    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
        </div>
    @endif


    @if ($message = Session::get('error'))
        <div class="alert alert-danger alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
        </div>
    @endif


    @if ($message = Session::get('warning'))
        <div class="alert alert-warning alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
        </div>
    @endif


    @if ($message = Session::get('info'))
        <div class="alert alert-info alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>
        </div>
    @endif


    @if ($errors->any())
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Please check the form below for errors
        </div>
    @endif

</div>

resources/views/frontend/theme/ui/includes/footer.blade.php
<!-- Footer Area Start -->
<footer class="evlis-footer-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-box">
                    <div class="footer-logo">
                        <a href="index.html"><img src="{{ asset('frontend/img/logo3.png') }}" alt="wrhc2020" /></a>
                    </div>
                    <div class="footer-copyright">
                        <p>Copyright &copy; Wonca.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Area End -->

resources/views/frontend/theme/ui/includes/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="17th WONCA World Rural Health Conference 2020">
    <meta name="keyword" content="conference,rural,health,wonca,rural-health">
    <meta name="author" content="Virtual-Echos Inc.">
    <!-- Title -->
    <title>@yield('title')  17th WONCA World Rural Health Conference 2020</title>
    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon.ico') }}">
    <!--Bootstrap css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/bootstrap.css') }} ">
    <!--Font Awesome css-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--Magnific css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/magnific-popup.css') }}">
    <!--Owl-Carousel css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('frontend/css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('frontend/slick/slick.css') }}"/>
    <!--Animate css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/animate.min.css') }}">
    <!--Flipclock css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/flipclock.css') }}">
    <!--Nice Select css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/nice-select.css') }}">
    <!--Site Main Style css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/style.css') }}">
    <!--Responsive css-->
    <link rel="stylesheet" href="{{ asset('frontend/css/responsive.css') }}">
</head>

resources/views/frontend/theme/ui/includes/navbar.blade.php
<!--Navbar Start-->
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <!-- LOGO -->
        <a class="navbar-brand logo" href="{{ route('frontend.index') }}">
            <img src="{{ asset('frontend/img/logo3.png') }}" alt="wonca" />
        </a>
        <a class="navbar-brand logo HideScroll" href="{{ route('frontend.index') }}">
            <img src="{{ asset('frontend/img/logo3.png') }}" alt="wrhc2020" />
        </a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{{ route('frontend.index') }}" class="nav-link" data-scroll-nav="0">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('abstract.frontend') }}" class="nav-link" >Abstract Submission</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('workshop.frontend') }}" class="nav-link" >Workshop & Scientific Paper</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" data-scroll-nav="3">schedule</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link" data-scroll-nav="4">speakers</a>
                </li>
                @guest
                <li class="nav-item">
                    <a href="{{ route('login') }}" class="nav-link" >Login</a>
                </li>
                @else
                <li class="nav-item">
                        <a href="{{ route('frontend.dashboard') }}" class="nav-link" >Dashboard</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                       class="nav-link" >{{ __('Logout') }} </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>

                </li>
                @endguest
            </ul>
            @guest
            <ul class="navbar-nav get_tickets">
                <li><a href="{{ route('frontend.registration') }}">Registration </a></li>
            </ul>
            @endguest
        </div>
    </div>
</nav>
<!--Navbar End-->

resources/views/frontend/theme/ui/includes/script.blade.php
<!--Jquery js-->
<script src="{{ asset('frontend/js/jquery.min.js') }}"></script>
<!-- Popper JS -->
<script src="{{ asset('frontend/js/popper.min.js') }}"></script>
<!--Bootstrap js-->
<script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
<!--ScrollIt js-->
<script src="{{ asset('frontend/js/scrollIt.min.js') }}"></script>
<!--Owl-Carousel js-->
<script src="{{ asset('frontend/js/owl.carousel.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('frontend/slick/slick.min.js') }}"></script>
<!--Ripples js-->
<script src="{{ asset('frontend/js/jquery.ripples-min.js') }}"></script>
<!--Flipclock js-->
<script src="{{ asset('frontend/js/flipclock.min.js') }}"></script>
<!--Nice Select js-->
<script src="{{ asset('frontend/js/jquery.nice-select.min.js') }}"></script>
<!--Magnific js-->
<script src="{{ asset('frontend/js/jquery.magnific-popup.min.js') }}"></script>
<!--Initial js-->
<script src="{{ asset('frontend/js/init.js') }}"></script>
<!--Main js-->
<script src="{{ asset('frontend/js/main.js') }}"></script>