routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.pages.home');
})->name('home');

Route::get('/abstract', function () {
    return view('frontend.pages.abstract');
})->name('abstract');
Route::get('/workshop', function () {
    return view('frontend.pages.workshop');
})->name('workshop');








Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
//   ->middleware('role:admin')
    ->group(function (){

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/registered-user', 'RegisteredUserController@index')->name('registered-user');
        Route::get('/registered-user/{id}', 'RegisteredUserController@show')->name('registered-user.show');
        Route::get('/abstract-submitted', 'AbstractController@index')->name('abstract-submitted');
        Route::get('/abstract-submitted/{id}', 'AbstractController@show')->name('abstract-submitted.show');
        Route::get('/workshop', 'WorkshopController@index')->name('workshop');
        Route::get('/workshop/{id}', 'WorkshopController@show')->name('workshop.show');
        Route::get('/subscriber', 'SubscriberController@index')->name('subscriber');
        Route::get('/subscriber/export', 'SubscriberController@export')->name('subscriber.export');

    Route::get('/add-important-date', 'ImportantDateController@create')->name('date.create');
    Route::post('/add-important-date', 'ImportantDateController@store')->name('date.store');
    Route::get('/important-dates', 'ImportantDateController@index')->name('dates');
    Route::post('/important-date-update', 'ImportantDateController@update')->name('date.update');
    Route::get('/important-date-destroy/{id}', 'ImportantDateController@destroy')->name('date.destroy');
    Route::get('/important-date-edit/{id}', 'ImportantDateController@show')->name('date.edit');

        Route::get('/add-speech', 'SpeechController@create')->name('speech.create');
        Route::post('/add-speech', 'SpeechController@store')->name('speech.store');
        Route::get('/speeches', 'SpeechController@index')->name('speeches');
        Route::post('/speech-update', 'SpeechController@update')->name('speech.update');
        Route::get('/speech-destroy/{id}', 'SpeechController@destroy')->name('speech.destroy');
        Route::get('/speech-edit/{id}', 'SpeechController@show')->name('speech.edit');

    Route::get('/add-slider', 'SliderController@create')->name('slider.create');
    Route::post('/add-slider', 'SliderController@store')->name('slider.store');
    Route::get('/sliders', 'SliderController@index')->name('sliders');
    Route::post('/slider-update', 'SliderController@update')->name('slider.update');
    Route::get('/slider-destroy/{id}', 'SliderController@destroy')->name('slider.destroy');
    Route::get('/slider-edit/{id}', 'SliderController@show')->name('slider.edit');


        Route::get('/add-schedule', 'ScheduleController@create')->name('schedule.create');
        Route::post('/add-schedule', 'ScheduleController@store')->name('schedule.store');
        Route::get('/schedules', 'ScheduleController@index')->name('schedules');
        Route::post('/schedule-update', 'ScheduleController@update')->name('schedule.update');
        Route::get('/schedule-destroy/{id}', 'ScheduleController@destroy')->name('schedule.destroy');
        Route::get('/schedule-edit/{id}', 'ScheduleController@show')->name('schedule.edit');






    });

Route::namespace('Backend')
  /*    ->middleware('role:user')*/
    ->group(function (){

        Route::get('/abstract','AbstractController@frontend' )->name('abstract.frontend');
        Route::post('/abstract','AbstractController@store' )->name('abstract.store');

        Route::get('/workshop','WorkshopController@frontend' )->name('workshop.frontend');
        Route::post('/workshop','WorkshopController@store' )->name('workshop.store');
    });


Route::name('frontend.')
        ->namespace('Frontend')
        ->group(function (){
            Route::get('/','IndexController@index' )->name('index');

            Route::get('/registration', function () {
                return view('frontend.pages.registration-detail');
            })->name('registration');

            Route::get('/dashboard','SinglePageController@dashboard' )->name('dashboard');

            Route::get('invitation', 'SinglePageController@invitation')->name('invitation');
            Route::get('tourism', 'SinglePageController@tourism')->name('tourism');
            Route::get('transportation', 'SinglePageController@transportation')->name('transportation');
            Route::get('attendees', 'SinglePageController@attendees')->name('attendees');
            Route::get('accommodations', 'SinglePageController@accommodations')->name('accommodations');


            Route::get('/payment-success','SinglePageController@payment_success' )->name('payment.success');
            Route::get('/payment-failed','SinglePageController@payment_fail' )->name('payment.failed');

            Route::get('/important-dates','SinglePageController@dates' )->name('dates');
            Route::get('/contact','SinglePageController@contact' )->name('contact');

            Route::post('/subscriber','IndexController@subscriber' )->name('subscriber.store');
        });



// SSLCOMMERZ Start
Route::get('/example1', 'SslCommerzPaymentController@exampleEasyCheckout');
Route::get('/example2', 'SslCommerzPaymentController@exampleHostedCheckout');

Route::post('/pay', 'SslCommerzPaymentController@index');
Route::post('/pay-via-ajax', 'SslCommerzPaymentController@payViaAjax');

Route::post('/success', 'SslCommerzPaymentController@success');
Route::post('/fail', 'SslCommerzPaymentController@fail');
Route::post('/cancel', 'SslCommerzPaymentController@cancel');

Route::post('/ipn', 'SslCommerzPaymentController@ipn');
//SSLCOMMERZ END

app/Http/Controllers/Backend/AbstractController.php
<?php

namespace App\Http\Controllers\Backend;

use App\AbstractSubmission;
use App\Http\Controllers\Controller;
use App\Mail\AbstractMail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class AbstractController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $registeredUser = AbstractSubmission::all();

        return view('backend.pages.abstract')->with([
            'users'=>$registeredUser
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }
    public function frontend()
    {

        if (Auth::guest()) {
            //is a guest so redirect
            return redirect('login');
        }

        else{
            return view('frontend.pages.abstract');
        }



    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $abstract = new AbstractSubmission();

        $abstract->uid = auth()->user()->id;
        $abstract->title = $request->title;
        $abstract->author =   $request->author;
        $abstract->abstract =  $request->abstract;
        $abstract->save();

        $data = $abstract;


        Mail::to(Auth::user()->email)->send(new AbstractMail($data));

        return back()->with('success','Abstract Submitted Successfully, Thank You.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $user = AbstractSubmission::where('id',$id)->firstOrFail();
        return view('backend.pages.abstract_details')->with([
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\AbstractSubmission;
use App\Http\Controllers\Controller;
use App\Subscriber;
use App\User;
use App\Workshop;
use DB;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

 /*       Role::create(['name'=>'admin']);
        Role::create(['name'=>'user']);*/

        $subs = Subscriber::count();
        $user = User::count();
        $abstract = AbstractSubmission::count();
        $workshop = Workshop::count();
        $order = DB::table('orders')->count();
        $bdt = DB::table('orders')
            ->where('currency','BDT')
            ->sum('amount');
        $usd = DB::table('orders')
            ->where('currency','USD')
            ->sum('amount');

//        dd($subs);

        return view('backend.pages.dashboard')->with([
            'subs' => $subs,
            'user' => $user,
            'abstract' => $abstract,
            'workshop' => $workshop,
            'order' => $order,
            'bdt' => $bdt,
            'usd' => $usd,

        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ImportantDateController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\ImportantDate;
use Illuminate\Http\Request;

class ImportantDateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $registeredUser = ImportantDate::all();

        return view('backend.pages.dates')->with([
            'users'=>$registeredUser
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.pages.add_date');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $abstract = new ImportantDate();

        $abstract->title =   $request->title;
        $abstract->details =  $request->details;

        $abstract->save();
        return redirect()->route('backend.dates');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $notice = ImportantDate::where('id',$id)->firstOrFail();


        return view('backend.pages.edit_date')->with([
            'user' => $notice
        ]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $abstract = ImportantDate::find($request->id);

        $abstract->title =   $request->title;
        $abstract->details =  $request->details;

        $abstract->save();
        return redirect()->route('backend.dates');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ImportantDate::find($id)->delete();
        return redirect()->route('backend.dates');
    }
}

app/Http/Controllers/Backend/RegisteredUserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class RegisteredUserController extends Controller
{
    /**
     *
     *
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $registeredUser = User::all();

        return view('backend.pages.registerd_user')->with([
            'users'=>$registeredUser
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::where('id',$id)->firstOrFail();
        return view('backend.pages.registerd_user_deatils')->with([
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SubscriberController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Subscriber;
use Illuminate\Http\Request;

use App\Exports\SubscribersExport;
use Maatwebsite\Excel\Facades\Excel;

class SubscriberController extends Controller
{
    public function index()
    {
        $registeredUser = Subscriber::all();

        return view('backend.pages.subscriber')->with([
            'users'=>$registeredUser
        ]);

    }
    public function export()
    {
        return Excel::download(new SubscribersExport, 'subscribers.xlsx');
    }
}

resources/views/backend/pages/abstract.blade.php
@extends('backend.theme.master')

@section('title','Dashboard')

@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Paper Abstrract</li>
    </ol>

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Paper Abstract <span class="badge badge-info"></span> </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Email</th>
                        <th>Title</th>
                        <th>Author</th>
                        <th>Action</th>
                    </tr>
                    </tfoot>
                    <tbody>

                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->user->email }} </td>
                            <td>{{ $user->title }}</td>
                            <td>{{ $user->author }}</td>
                            <td><a href="{{ route('backend.abstract-submitted.show',['id'=> $user->id]) }}" class="btn btn-primary">View</a></td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer small text-muted"> </div>
    </div>




 @endsection

resources/views/backend/pages/dashboard.blade.php
@extends('backend.theme.master')

@section('title','Dashboard')

@section('content')


    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('backend.dashboard') }}">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Overview</li>
    </ol>

    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-mail-bulk"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $subs }}</h3> </div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('backend.subscriber') }}">
                    <span class="float-left">Subscriber</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-dark o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-user-check"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $user }}</h3> </div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('backend.registered-user')}}">
                    <span class="float-left">Total Registered User</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-file-pdf"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $abstract }}</h3></div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('backend.abstract-submitted') }}">
                    <span class="float-left">Abstract Submitted</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-book-medical"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $workshop }}</h3></div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ route('backend.workshop') }}">
                    <span class="float-left">Workshop & Scientific Paper</span>
                    <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-bell"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $order }}</h3></div>
                </div>
                <a class="card-footer text-white clearfix small z-1">
                    <span class="float-left">Registration Paid by</span>
                    <span class="float-right">
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-info o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-money-bill"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $bdt }} ৳</h3></div>
                </div>
                <a class="card-footer text-white clearfix small z-1">
                    <span class="float-left">Amount Received (BDT) </span>
                    <span class="float-right">
                </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-dark o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fas fa-fw fa-money-bill-wave-alt"></i>
                    </div>
                    <div class="mr-5"><h3>{{ $usd }} $</h3></div>
                </div>
                <a class="card-footer text-white clearfix small z-1">
                    <span class="float-left">Amount Received (USD) </span>
                    <span class="float-right">
                </span>
                </a>
            </div>
        </div>
    </div>

{{--    <div class="row">--}}
{{--        <div class="col-xl-3 col-sm-6 mb-3">--}}
{{--            <div class="card text-white bg-primary o-hidden h-100">--}}
{{--                <div class="card-body">--}}

{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}





@endsection

resources/views/backend/pages/edit_date.blade.php
@extends('backend.theme.master')

@section('title','Dashboard')

@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active"> Important Dates</li>
    </ol>


    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user"></i>
           Add New Important Dates
        </div>
        <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.date.update') }}" method="post"
              enctype="multipart/form-data">
            @csrf
            <input type="hidden" class="form-control"  name="id" value="{{ $user->id }}" >
        <div class="card-body">
            <table class="table table-responsive table-hover">

                <tr>
                    <td class="bg-info">Title</td>
                    <td  class="col-12 ">
                        <input type="text"  class="col-12 form-control"  value="{{ $user->title }}" name="title">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Details</td>
                    <td  class="col-12 ">
                        <input type="text"  class="col-12 form-control"  value="{{ $user->details }}"  name="details">
                    </td>
                </tr>

            </table>
        </div>
        <div class="card-footer small text-right">
            <a href="{{ route('backend.date.destroy',['id'=> $user->id]) }}" class="btn btn-default">Delete</a>
                <input type="submit" name="delete" value="Update" class="btn btn-success">
        </div>
            </form>

    </div>

 @endsection

resources/views/backend/pages/edit_schedule.blade.php
@extends('backend.theme.master')

@section('title','Dashboard')

@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Schedule</li>
    </ol>


    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user"></i>
           Add New Schedule
        </div>
        <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.schedule.store') }}" method="post"
              enctype="multipart/form-data">
            @csrf
            <input type="hidden" class="form-control"  name="id" value="{{ $user->id }}" >
        <div class="card-body">
            <table class="table table-responsive table-hover">
                <tr>
                    <td class="bg-info">Select Day</td>
                    <td  class="col-12 ">
                        <select name="day">
                            <option {{$user->day=="day1"? 'selected':''}} name="day" value="day1">Day 1</option>
                            <option {{$user->day=="day2"? 'selected':''}}  name="day" value="day2">Day 2</option>
                            <option {{$user->day=="day3"? 'selected':''}} name="day" value="day3">Day 3</option>
                            <option {{$user->day=="day4"? 'selected':''}} name="day" value="day4">Day 4</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Title</td>
                    <td  class="col-12 ">
                        <input  class="col-12 form-control " value="{{ $user->title }}"  type="text" name="title">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Time</td>
                    <td  class="col-12 ">
                        <input  class="col-12 form-control " value="{{ $user->time }}"  type="text" name="time">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Text</td>
                    <td  class="col-12 ">
                        <input  class="col-12 form-control " value="{{ $user->text }}"  type="text" name="text">
                    </td>
                </tr>


            </table>
        </div>
            <div class="card-footer small text-right">
                <a href="{{ route('backend.schedule.destroy',['id'=> $user->id]) }}" class="btn btn-default">Delete</a>
                <input type="submit" value="Update" class="btn btn-success">
            </div>
            </form>

    </div>

 @endsection

resources/views/backend/pages/edit_speech.blade.php
@extends('backend.theme.master')

@section('title','Dashboard')

@section('content')

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Speaker</li>
    </ol>


    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-user"></i>
           Add New Speech
        </div>
        <form accept-charset="UTF-8" class="form-horizontal" action="{{ route('backend.speech.update') }}" method="post"
              enctype="multipart/form-data">
            @csrf
            <input type="hidden" class="form-control"  name="id" value="{{ $user->id }}" >
        <div class="card-body">
            <table class="table table-responsive table-hover">
                <tr>
                    <td class="bg-info">Speaker Type</td>
                    <td  class="col-12 ">
                        <select name="speaker_type">
                            <option {{$user->speaker_type=="front_speaker"? 'selected':''}} name="speaker_type" value="front_speaker">Front Speaker</option>
                            <option {{$user->speaker_type=="keynote_speaker"? 'selected':''}}  name="speaker_type" value="keynote_speaker">Keynote Speaker</option>
                            <option {{$user->speaker_type=="normal_speaker"? 'selected':''}}   name="speaker_type" value="normal_speaker">Normal Speaker</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Speaker Name</td>
                    <td  class="col-12 ">
                        <input  class="col-12 form-control "  value="{{ $user->speaker_name }}" type="text" name="speaker_name">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Speaker Details</td>
                    <td  class="col-12 ">
                        <input  class="col-12 form-control "  value="{{ $user->speaker_details }}" type="text" name="speaker_details">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Image</td>
                    <td  class="col-12 ">
                        <img src="{{ asset("uploads/".$user->speaker_image)  }}" alt="" width="100px" height="100px">
                        <input type="file"  class="col-12 form-control"  name="speaker_image">
                    </td>
                </tr>
                <tr>
                    <td class="bg-info">Speech</td>
                    <td  class="col-12 ">
                        <textarea class="form-control"  name="speech" rows="4" spellcheck="false">{{ $user->speech }}</textarea>
                    </td>
                </tr>

            </table>
        </div>
        <div class="card-footer small text-right">
            <a href="{{ route('backend.speech.destroy',['id'=> $user->id]) }}" class="btn btn-default">Delete</a>
                <input type="submit" value="Update" class="btn btn-success">
        </div>
            </form>

    </div>

 @endsection