routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.pages.home');
})->name('home');

Route::get('/abstract', function () {
    return view('frontend.pages.abstract');
})->name('abstract');
Route::get('/workshop', function () {
    return view('frontend.pages.workshop');
})->name('workshop');








Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::name('backend.')
    ->namespace('Backend')
    ->prefix('admin')
//   ->middleware('role:admin')
    ->group(function (){

        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/registered-user', 'RegisteredUserController@index')->name('registered-user');
        Route::get('/registered-user/{id}', 'RegisteredUserController@show')->name('registered-user.show');
        Route::get('/abstract-submitted', 'AbstractController@index')->name('abstract-submitted');
        Route::get('/abstract-submitted/{id}', 'AbstractController@show')->name('abstract-submitted.show');
        Route::get('/workshop', 'WorkshopController@index')->name('workshop');
        Route::get('/workshop/{id}', 'WorkshopController@show')->name('workshop.show');
        Route::get('/subscriber', 'SubscriberController@index')->name('subscriber');
        Route::get('/subscriber/export', 'SubscriberController@export')->name('subscriber.export');

    Route::get('/add-important-date', 'ImportantDateController@create')->name('date.create');
    Route::post('/add-important-date', 'ImportantDateController@store')->name('date.store');
    Route::get('/important-dates', 'ImportantDateController@index')->name('dates');
    Route::post('/important-date-update', 'ImportantDateController@update')->name('date.update');
    Route::get('/important-date-destroy/{id}', 'ImportantDateController@destroy')->name('date.destroy');
    Route::get('/important-date-edit/{id}', 'ImportantDateController@show')->name('date.edit');

        Route::get('/add-speech', 'SpeechController@create')->name('speech.create');
        Route::post('/add-speech', 'SpeechController@store')->name('speech.store');
        Route::get('/speeches', 'SpeechController@index')->name('speeches');
        Route::post('/speech-update', 'SpeechController@update')->name('speech.update');
        Route::get('/speech-destroy/{id}', 'SpeechController@destroy')->name('speech.destroy');
        Route::get('/speech-edit/{id}', 'SpeechController@show')->name('speech.edit');

    Route::get('/add-slider', 'SliderController@create')->name('slider.create');
    Route::post('/add-slider', 'SliderController@store')->name('slider.store');
    Route::get('/sliders', 'SliderController@index')->name('sliders');
    Route::post('/slider-update', 'SliderController@update')->name('slider.update');
    Route::get('/slider-destroy/{id}', 'SliderController@destroy')->name('slider.destroy');
    Route::get('/slider-edit/{id}', 'SliderController@show')->name('slider.edit');


        Route::get('/add-schedule', 'ScheduleController@create')->name('schedule.create');
        Route::post('/add-schedule', 'ScheduleController@store')->name('schedule.store');
        Route::get('/schedules', 'ScheduleController@index')->name('schedules');
        Route::post('/schedule-update', 'ScheduleController@update')->name('schedule.update');
        Route::get('/schedule-destroy/{id}', 'ScheduleController@destroy')->name('schedule.destroy');
        Route::get('/schedule-edit/{id}', 'ScheduleController@show')->name('schedule.edit');






    });

Route::namespace('Backend')
  /*    ->middleware('role:user')*/
    ->group(function (){

        Route::get('/abstract','AbstractController@frontend' )->name('abstract.frontend');
        Route::post('/abstract','AbstractController@store' )->name('abstract.store');

        Route::get('/workshop','WorkshopController@frontend' )->name('workshop.frontend');
        Route::post('/workshop','WorkshopController@store' )->name('workshop.store');
    });


Route::name('frontend.')
        ->namespace('Frontend')
        ->group(function (){
            Route::get('/','IndexController@index' )->name('index');

            Route::get('/registration', function () {
                return view('frontend.pages.registration-detail');
            })->name('registration');

            Route::get('/dashboard','SinglePageController@dashboard' )->name('dashboard');

            Route::get('invitation', 'SinglePageController@invitation')->name('invitation');
            Route::get('tourism', 'SinglePageController@tourism')->name('tourism');
            Route::get('transportation', 'SinglePageController@transportation')->name('transportation');
            Route::get('attendees', 'SinglePageController@attendees')->name('attendees');
            Route::get('accommodations', 'SinglePageController@accommodations')->name('accommodations');


            Route::get('/payment-success','SinglePageController@payment_success' )->name('payment.success');
            Route::get('/payment-failed','SinglePageController@payment_fail' )->name('payment.failed');

            Route::get('/important-dates','SinglePageController@dates' )->name('dates');
            Route::get('/contact','SinglePageController@contact' )->name('contact');

            Route::post('/subscriber','IndexController@subscriber' )->name('subscriber.store');
        });



// SSLCOMMERZ Start
Route::get('/example1', 'SslCommerzPaymentController@exampleEasyCheckout');
Route::get('/example2', 'SslCommerzPaymentController@exampleHostedCheckout');

Route::post('/pay', 'SslCommerzPaymentController@index');
Route::post('/pay-via-ajax', 'SslCommerzPaymentController@payViaAjax');

Route::post('/success', 'SslCommerzPaymentController@success');
Route::post('/fail', 'SslCommerzPaymentController@fail');
Route::post('/cancel', 'SslCommerzPaymentController@cancel');

Route::post('/ipn', 'SslCommerzPaymentController@ipn');
//SSLCOMMERZ END

resources/views/backend/theme/ui/includes/footer.blade.php
<footer class="sticky-footer">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright by <a href="https://virtualechos.com/">Virtual Echos Inc</a> ©2019</span>
        </div>
    </div>
</footer>

resources/views/backend/theme/ui/includes/head.blade.php
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - Panel</title>

    <!-- Custom fonts for this template-->
    <link href="{{ asset('backend/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{{ asset('backend/vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{{ asset('backend/css/sb-admin.css') }}" rel="stylesheet">
    <script src='https://cdn.tiny.cloud/1/75k92kh1smx0pousjzd5g8iaclomgl9erkv5bytaqro2q7f6/tinymce/5/tinymce.min.js' referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>

</head>

resources/views/backend/theme/ui/includes/modal.blade.php
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>



                <a class="btn btn-primary" href="{{ route('logout') }}"  onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Logout</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/backend/theme/ui/includes/navbar.blade.php
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="#">WRHC2020</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->


</nav>

resources/views/backend/theme/ui/includes/script.blade.php
<script src="{{ asset('backend/vendor/jquery/jquery.min.js') }} "></script>
<script src="{{ asset('backend/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('backend/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Page level plugin JavaScript-->
<script src="{{ asset('backend/vendor/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('backend/vendor/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('backend/vendor/datatables/dataTables.bootstrap4.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('backend/js/sb-admin.min.js') }}"></script>

<!-- Demo scripts for this page-->
<script src="{{ asset('backend/js/demo/datatables-demo.js') }}"></script>
<script src="{{ asset('backend/js/demo/chart-area-demo.js') }}"></script>
<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .then( editor => {
            console.log( editor );
        } )
        .catch( error => {
            console.error( error );
        } );
</script>

resources/views/backend/theme/ui/includes/sidebar.blade.php
<ul class="sidebar navbar-nav">
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('backend.dashboard') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('backend.registered-user')}}">
            <i class="fas fa-fw fa-address-book"></i>
            <span>Registered User</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('backend.abstract-submitted')}}">
            <i class="fas fa-fw fa-certificate"></i>
            <span>Abstract Submitted</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('backend.workshop')}}">
            <i class="fas fa-fw fa-book-reader"></i>
            <span>Workshop</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{route('backend.subscriber')}}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Subscriber</span></a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-user"></i>
            <span>Speakers</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(5px, 56px, 0px);">

            <a class="dropdown-item" href="{{route('backend.speeches')}}">All Speakers</a>
            <a class="dropdown-item" href="{{route('backend.speech.create')}}">Add New Speaker</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-sliders-h"></i>
            <span>Sliders</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(5px, 56px, 0px);">

            <a class="dropdown-item" href="{{route('backend.sliders')}}">All Sliders</a>
            <a class="dropdown-item" href="{{route('backend.slider.create')}}">Add New Slider</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-calendar-alt"></i>
            <span>Important Dates</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(5px, 56px, 0px);">

            <a class="dropdown-item" href="{{route('backend.dates')}}">All Important Dates</a>
            <a class="dropdown-item" href="{{route('backend.date.create')}}">Add New  Date</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-calendar-day"></i>
            <span>Schedules</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(5px, 56px, 0px);">

            <a class="dropdown-item" href="{{route('backend.schedules')}}">All Schedules</a>
            <a class="dropdown-item" href="{{route('backend.schedule.create')}}">Add New Schedule</a>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link"  href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-fw fa-times-circle"></i>
            <span>Logout</span></a>
    </li>
</ul>